<?php
declare(strict_types=1);

// SxpVpn SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

SxpVpnUtility::setRegistrar(function (SxpVpnUtility $u): void {
    $u->clean = [SxpVpnClean::class, 'call'];
    $u->done = [SxpVpnDone::class, 'call'];
    $u->make_error = [SxpVpnMakeError::class, 'call'];
    $u->feature_add = [SxpVpnFeatureAdd::class, 'call'];
    $u->feature_hook = [SxpVpnFeatureHook::class, 'call'];
    $u->feature_init = [SxpVpnFeatureInit::class, 'call'];
    $u->fetcher = [SxpVpnFetcher::class, 'call'];
    $u->make_fetch_def = [SxpVpnMakeFetchDef::class, 'call'];
    $u->make_context = [SxpVpnMakeContext::class, 'call'];
    $u->make_options = [SxpVpnMakeOptions::class, 'call'];
    $u->make_request = [SxpVpnMakeRequest::class, 'call'];
    $u->make_response = [SxpVpnMakeResponse::class, 'call'];
    $u->make_result = [SxpVpnMakeResult::class, 'call'];
    $u->make_point = [SxpVpnMakePoint::class, 'call'];
    $u->make_spec = [SxpVpnMakeSpec::class, 'call'];
    $u->make_url = [SxpVpnMakeUrl::class, 'call'];
    $u->param = [SxpVpnParam::class, 'call'];
    $u->prepare_auth = [SxpVpnPrepareAuth::class, 'call'];
    $u->prepare_body = [SxpVpnPrepareBody::class, 'call'];
    $u->prepare_headers = [SxpVpnPrepareHeaders::class, 'call'];
    $u->prepare_method = [SxpVpnPrepareMethod::class, 'call'];
    $u->prepare_params = [SxpVpnPrepareParams::class, 'call'];
    $u->prepare_path = [SxpVpnPreparePath::class, 'call'];
    $u->prepare_query = [SxpVpnPrepareQuery::class, 'call'];
    $u->graphql_body = [SxpVpnGraphql::class, 'body'];
    $u->graphql_errors = [SxpVpnGraphql::class, 'errors'];
    $u->result_basic = [SxpVpnResultBasic::class, 'call'];
    $u->result_body = [SxpVpnResultBody::class, 'call'];
    $u->result_headers = [SxpVpnResultHeaders::class, 'call'];
    $u->transform_request = [SxpVpnTransformRequest::class, 'call'];
    $u->transform_response = [SxpVpnTransformResponse::class, 'call'];
});
